### PR TITLE
Added SCD30 driver [feature]

### PR DESCRIPTION
**Pull request by RoccoDevs**
Added drivers for the SCD30 CO2 sensor. I only just started using Meadow.Foundation, so if there's anything I'm doing that's not within the usual please let me know.

### CODE REVIEW

**Comment by adrianstevens** [comment]
At first glace this looks fantastic! I'll go through it in detail this week and I'll order a sensor to test.

**Comment by RoccoDevs** [comment]
> At first glace this looks fantastic! I'll go through it in detail this week and I'll order a sensor to test.

Thanks, I have been running it since I created the PR. And I've since had an error: `UnhandledException` followed by:  `Meadow.NativeException: Communication error. Verify address and that SCL and SDA are not reversed.`

I'm not sure what causes it and I'll have a look at it later. Does the meadow support clock stretching?

**Comment by adrianstevens** [comment]
Meadow does support clock stretching. Are you seeing that issue consistently or intermittently?

**Comment by RoccoDevs** [comment]
> Are you seeing that issue consistently or intermittently?
It always happens, but sometimes after an hour and other times after many more hours. 
> Meadow does support clock stretching. 
The reason I asked is because the interface description says it has to be supported. I did assume the Meadow supported it, but because of this seemingly random issue I wanted to be sure.

**Comment by adrianstevens** [comment]
Interesting ... sounds like I need to order hardware and test

**Comment by RoccoDevs** [comment]
I have not really had time to debug it. I may be able to on the weekend, but I'm glad you are also willing to look into it!

**Comment by adrianstevens** [comment]
I'm going to merge since the driver is complete this may be an issue somewhere else in the stack

**Review by adrianstevens — APPROVED** [review]

**Comment by RoccoDevs** [comment]
> I'm going to merge since the driver is complete this may be an issue somewhere else in the stack

Alright thanks, I've not really had the time to work on my project with this sensor. Whenever I have time and run into the problem again I'll look into debugging it (if it hasn't been fixed by then)

**Pull request merged**
