### PR TITLE
Update PixelBufferBase.cs

### PR DESCRIPTION
**Pull request by UeberDaniel**
Added "ColorMode.Format24bppGrb888 => 24" for using a Grb888 buffer.

### CODE REVIEW

**Review by adrianstevens — APPROVED** [review]

**Comment by adrianstevens** [comment]
Thanks @UeberDaniel - do we also need to add a BufferGbr888 class?

**Review by adrianstevens — COMMENTED** [review]
Just need to retarget to develop - I think I can just cherry pick the

**Comment by UeberDaniel** [comment]
@adrianstevens no, I just need it for the https://github.com/UeberDaniel/Ws2812Display/blob/master/driver/Ws2812ScreenBufferGrb888.cs

**Comment by adrianstevens** [comment]
perfect :)

**Pull request merged**
