### PR TITLE
Move and upgrade DataLoggers* projects

### PR DESCRIPTION
**Pull request by patridge**
Looks like these projects were living off on their own in the solution, which left them out of some of the upgrade fun. I moved DataLoggers and DataLoggers.* projects into the Peripheral_Libs solution item and upgraded them to the latest csproj format with latest NuGet packages.

### CODE REVIEW

**Comment by jorgedevs** [comment]
Hey Adam,

Could you please also rename the project name Dataloggers.ThingSpeak? the csproj file name is:

Source/Peripheral_Libs/DataLoggers.ThingSpeak/DataLoggers.ThingSpeak.csproj

I think it should be:

Source/Peripheral_Libs/DataLoggers.ThinkSpeak/DataLoggers.ThinkSpeak.csproj

Other than that, everything looks good :)

**Comment by patridge** [comment]
@jorgedevs Will do. I don't know that I changed that, but I will definitely fix it.

**Comment by patridge** [comment]
@jorgedevs I double-checked the name. Looks like it should be ["ThingSpeak"](https://thingspeak.com), so I updated the csproj fields rather than the filenames.

**Comment by jorgedevs** [comment]
Yeah, I noticed that too. Thanks for double checking,

**Pull request merged**
